### ISSUE TITLE
Updated for 4.0.5

### ISSUE THREAD

**Issue by calvinchengx** [jeremy-w/objc-zmq#18]
I have updated for libzmq 4.0.5 if you are interested to merge back into your mainline?

Reference https://github.com/calvinchengx/objc-zmq/commit/7ebc97b4c3191b07b40d4d852048f4af02c9b299

**Comment by jeremy-w** [comment]
:+1: Want to open a PR?

**Comment by jeremy-w** [comment]
Opened it directly and merged. Thanks a lot!
