### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by flagsoft** [jeremy-w/objc-zmq#20]
There is no source code of Zero MQ within this package ?
I was able to create the .a file with your script or within Xcode, and now? Where are the functions connect, bind, send, recve?

**Comment by jeremy-w** [comment]
objc-zmq is bundled with a pre-compiled version of libzmq. It's currently built against v4.0.5. You'll find that in the tree here: https://github.com/jeremy-w/objc-zmq/tree/master/Library/zeromq-4.0.5/static

Endpoint configuration and communication are exposed via the `ZMQSocket` class, see: https://github.com/jeremy-w/objc-zmq/blob/master/Classes/objc-zmq/ZMQSocket.h#L35-L45
