### ISSUE TITLE
ZMQException on setting ZMQ_CURVE_SECRETKEY value on a ZMQSocket

### ISSUE THREAD

**Issue by candeias** [jeremy-w/objc-zmq#21]
Hi,

I'm trying to implement the CURVE authentification using objc-zmq, and when I try to sent any of the ZMQ_CURVE_* options on a socket I get this exception:

Terminating app due to uncaught exception 'ZMQException', reason: 'No such process'

Is CURVE supported? is using the - (BOOL)setData:(NSData *)data forOption:(ZMQSocketOption)option the right function call to set this kind of data?

Any help is appreciated!

**Comment by jeremy-w** [comment]
Can you share a demo project? The Obj-C ZMQ layer is pretty slim, so it should let you do whatever you can do with the C version.
