### ISSUE TITLE
Installing via CocoaPods in an OS X (NOT iOS) project should work out of the box

### ISSUE THREAD

**Issue by landongn** [jeremy-w/objc-zmq#22]
<img width="812" alt="screenshot 2015-10-22 16 57 07" src="https://cloud.githubusercontent.com/assets/578681/10681433/13f08a88-78de-11e5-99dd-e9c0b3474065.png">

It would seem the included .a file is statically built for only supporting arm environments, rather than x86.  Would be nice to have an option to build the .a file yourself in a bash script or something, or include a universal binary instead.

**Comment by jeremy-w** [comment]
I see the Podfile says OS X is supported, but the static lib that comes bundled with it doesn't play along with that.

**Comment by jeremy-w** [comment]
Retitled to describe the problem.

**Comment by jeremy-w** [comment]
If someone issues a PR with a cross-platform staticlib, I'll happily declare support for OS X in the podspec again. Absent that level of interest, adjusting it to match the current reality seems the best course of action.
